name: Build geosite.dat

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 03:00 AM UTC = 10:00 AM Vietnam Time

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Set variables
        run: |
          TZ="Asia/Ho_Chi_Minh"
          RELEASE_NAME=$(TZ=$TZ date '+%d/%m/%Y %H:%M')
          TAG_NAME=$(TZ=$TZ date '+%Y%m%d%H%M')
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        shell: bash

      - name: Build geosite.dat file
        run: |
          cd code || exit 1
          mkdir -p data
          curl -sSL https://raw.githubusercontent.com/Thaomtam/Geosite-vn/rule-set/tenmien.json | sort -u | sed '/^$/d' > data/category-ads-all
          curl -sSL https://raw.githubusercontent.com/bigdargon/hostsVN/refs/heads/master/extensions/adult/domain.txt | sort -u | sed '/^$/d' > data/porn
          go run ./ --outputdir=../ --exportlists=category-ads-all,porn --datapath=data
          cd ../ && rm -rf code
          mv dlc.dat geosite.dat

      - name: Generate geosite.dat sha256 hash
        run: |
          sha256sum geosite.dat > geosite.dat.sha256sum

      - name: Generate Zip
        run: |
          zip -9 geosite.dat.zip geosite.dat
          sha256sum geosite.dat.zip > geosite.dat.zip.sha256sum

      - name: Generate XZ
        run: |
          xz -z -9 -k geosite.dat
          sha256sum geosite.dat.xz > geosite.dat.xz.sha256sum

      - name: Create release notes file
        run: |
          echo -e "👉 Github: thaomtam\n👉 Facebook: thời tiết\n👉 Telegram: t.me/ktandroidreview\n\n😍😍 Bộ geositeVN cho người Việt" > release-notes.txt

      - name: Git push assets to "release" branch
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add *.txt *.sha256sum geosite.dat geosite.dat.zip geosite.dat.xz release-notes.txt
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --generate-notes \
            --latest \
            --title "Build bởi Thời Tiết - ${{ env.RELEASE_NAME }}" \
            --notes-file release-notes.txt \
            ./geosite.dat ./geosite.dat.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
